merged from PC

diff --git a/bin/dmenu-virt b/bin/dmenu-virt
--- a/bin/dmenu-virt
+++ b/bin/dmenu-virt
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #  ____     _ 
 # |  _ \   | |
 # | |_) |  | |
@@ -8,18 +8,116 @@
 
 set -e
 
+command -v gum >/dev/null 2>&1
+[ "${?}" -ne 0 ] && echo "Install gum, see https://github.com/charmbracelet/gum" >&2 && exit 2
+
+# varaibles {{{
+prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+# }}}
+# help function {{{
+help() {
+cat << EOF
+${prompt}: what problem is this script solving
+
+usage: [-h] [-i input] [-o output]
+
+   • arguemts:
+       -i --input      intput x
+       -o --output     output y
+       -s --style      launcher style
+       -e --args       extra args (to pass to the launcher)
+       -h --help       print this message
+
+   • example:
+       ${prompt} -i in -o out
+
+   • running without any arguments will show this message
+EOF
+}
+# }}}
+
+# argument parsing {{{
+while [ "${#}" -gt 0 ]; do
+case ${1} in
+	-h|--help)
+		help
+		exit 0
+		;;
+	-d|--dir)
+		rootdir="${2}"
+		shift
+		;;
+	-a|--args)
+		args="${2}"
+		shift
+		;;
+	*)
+		echo "Unknown parameter passed: ${1}"
+		exit 1
+		;;
+esac
+shift
+done
+# }}}
+# checking args {{{
+[ -z "${rootdir}" ] && rootdir="${HOME}/vm"
+# }}}
+
+# notification function {{{
 notify() {
-	notify-send -a dmvirt -i qemu-system "${1}" "${2}"
+summary="${1}"
+if [ -z "${2}" ] || [ "${2}" = 1 ] || [ "${2}" = 2 ] || [ "${2}" = 3 ]; then
+	case ${2} in
+		1) mode=low ;;
+		2) mode=normal ;;
+		3) mode=critical ;;
+		*) mode=normal ;;
+	esac
+	#msgbody="${3}"
+else
+	case ${3} in
+		1) mode=low ;;
+		2) mode=normal ;;
+		3) mode=critical ;;
+		*) mode=normal ;;
+	esac
+	msgbody="${2}"
+fi
+
+if [ ${mode} = 'critical' ]; then
+	iferror="stderr"
+#		icon='error'
+else
+	iferror="stdout"
+fi
+
+if [ -n "${icon}" ]; then
+	noticon="-i ${icon}"
+fi
+
+if [ "${style}" = 'tui' ]; then
+	printf '[%s] %s\n' "${summary}" "${msgbody}" "${iferror}"
+elif [ -z "${DISPLAY}" ]; then
+	echo "${@}" >/dev/null 2>&1
+else
+	notify-send -a "${prompt}" -u ${mode} ${noticon} \
+		"${summary}" "${msgbody}" 2>/dev/null
+	printf '[%s] %s\n' "${summary}" "${msgbody}" >/dev/${iferror}
+fi
+}
+# }}}
+
+notify() {
+	notify-send -a ${prompt} -i qemu-system "${1}" "${2}"
 	printf '%s: %s\n' "${1}" "${2}" 1>&2
 }
 
-path="${HOME}/.local/virtual-machines/qemu"
+path="${rootdir}"
 
 patched=$(dmenu -v | grep -c 'hos-patched')
 if [ ${patched} -eq 1 ]; then
-	patches="-c -bw 2 -g 1 -l 11 -r"
+	patches="-c -bw 2 -g 2 -l 3 -r"
 fi
-prompt="virt"
 runner="dmenu \
 		-i \
 		${patches} \
@@ -27,23 +125,57 @@ runner="dmenu \
 		${@} \
 		"
 
-list=$(find ${path} -maxdepth 1 -type d \
-	| grep -v "${path}$\|manage.sh" \
+list=$(find ${path} -mindepth 1 -maxdepth 1 -type d \
 	| awk -F '/' '{print $NF;}' \
-	| grep -v '\.' \
-	| grep -v '_')
+	| grep -v '_' \
+	| grep -v '\.iso$' \
+)
 
-vm_name=$(echo ${list} | tr ' ' '\n' | ${runner})
+ps_names=$(ps aux \
+	| grep -v grep \
+	| grep qemu-system \
+	| awk '{print $NF;}' \
+    | sed 's/\.img.*//' \
+    | sed 's,^\./,,' \
+)
+
+for i in $(echo ${list} | tr ' ' '\n'); do
+    for j in ${ps_names}; do
+        if [ "${i}" = "${j}" ]; then
+            list=$(echo ${list} | sed "s/${i}/${i}:[on]/")
+        fi
+    done
+done
+
+vm_name=$(echo ${list} | tr ' ' '\n' | sort | ${runner})
+
+echo ${vm_name}
+[ -z "${vm_name}" ] && $0
+
+path=$(echo ${path} | awk -F ':' '{print $1;}')
+vm_status=${vm_name}
+vm_name=$(echo ${vm_name}  | awk -F ':' '{print $1;}')
 
 options=$(find ${path}/${vm_name} -maxdepth 1 -type f -perm /u+x \
-	| awk -F '/' '{print $NF;}')
+	| awk -F '/' '{print $NF;}' \
+	| grep -v '\.iso$' \
+)
+
+echo ${options}
+[ -z "${options}" ] && $0
 
 if [ -z "${options}" ]; then
 	notify "${vm_name}" "No executable found. Nothing to do here"
 	exit 1
 fi
 
-run=$(echo ${options} | tr ' ' '\n' | ${runner} -p ${vm_name}-${prompt})
+if [ ${patched} -eq 1 ]; then
+	patches="-l 2"
+fi
+run=$(echo ${options} | tr ' ' '\n' | ${runner} ${patches} -p vm:${vm_status})
+
+echo ${run}
+[ -z "${run}" ] && $0
 
 # echo "${path}/${vm_name}/${run}"
 
diff --git a/bin/nmdns b/bin/nmdns
--- a/bin/nmdns
+++ b/bin/nmdns
@@ -16,69 +16,76 @@ usage: [-hsep] [-print] [-i dns]
        -i         set specified DNS
        -s         set Shekan
        -e         set Electro
+       -n         set Norm
        -h         print this message
        -p -print  print current DNS
 
    • example:
-       ${prompt} -i '8.8.8.8'
+       ${prompt} -i 8.8.8.8 4.2.2.4
 
-   • running without any arguments will set DNS to 4.2.2.4
+   • running without any arguments will set DNS to 4.2.2.4 and 8.8.8.8
 EOF
 }
 # }}}
 
 # set function {{{
 setdns() {
-    verbose=false
+	verbose=false
+	default_servers="192.168.18.4 192.168.18.6"
 
-    case "${1}" in
-        -i)
-            shift
-            if [ "${#}" -gt 0 ]; then
-                servers="${@}"
-            else
-                printf '%s %s\n' \
-                    "${prompt}: WARNING: no DNS were provided" \
-                    "falling back to defaults" > /dev/stderr
-                servers="8.8.8.8 4.2.2.4"
-            fi
-            ;;
-        -e) servers="78.157.42.101 78.157.42.100" ;;
-        -s) servers="178.22.122.100 185.51.200.2" ;;
-        -h) echo Help is not implemented yet; exit 6 ;;
-        *) servers="8.8.8.8 4.2.2.4" ;;
-    esac
+	case "${1}" in
+		-i)
+			shift
+			if [ "${#}" -gt 0 ]; then
+				servers="${@}"
+			else
+				printf '%s %s\n' \
+					"${prompt}: WARNING: no DNS were provided" \
+					"falling back to defaults" > /dev/stderr
+				servers="${default_servers}"
+			fi
+			;;
+		-e) servers="78.157.42.101 78.157.42.100" ;;
+		-n) servers="4.2.2.4 8.8.8.8" ;;
+		-s) servers="178.22.122.100 185.51.200.2" ;;
+		-h) echo Help is not implemented yet; exit 6 ;;
+		*)
+			echo "${prompt}: Invalid arguments: [${@}]"
+			servers="${default_servers}"
+		;;
+	esac
 
-    [ ${verbose} = 'true' ] && printf '[DNS]: %s\n' ${servers}
+	[ ${verbose} = 'true' ] && printf '[DNS]: %s\n' ${servers}
 
-    echo "${prompt}: setting DNS [${servers}]..."
-    nmcli -g name,type connection  show  --active \
-        | awk -F: '/ethernet|wireless/ { print $1; }' \
-        | while read connection; do
-        nmcli con mod "${connection}" ipv6.ignore-auto-dns yes
-        nmcli con mod "${connection}" ipv4.ignore-auto-dns yes
-        nmcli con mod "${connection}" ipv4.dns "${servers}"
-        nmcli con down "${connection}" && nmcli con up "${connection}"
-    done
+	echo "${prompt}: setting DNS [${servers}]..."
+	nmcli -g name,type connection  show  --active \
+		| awk -F: '/ethernet|wireless/ { print $1; }' \
+		| while read connection; do
+		nmcli con mod "${connection}" ipv6.ignore-auto-dns yes
+		nmcli con mod "${connection}" ipv4.ignore-auto-dns yes
+		nmcli con mod "${connection}" ipv4.dns "${servers}"
+		nmcli con down "${connection}" && nmcli con up "${connection}"
+	done
 
-    # add 34 to your signal
-    ${reloaddwmblocks} 2>/dev/null
+	# add 34 to your signal
+	${reloaddwmblocks} 2>/dev/null
 }
 # }}}
 
 # print function {{{
 printdns() {
-    device="${1}"
-    printf '[DNS]: %s\n' $(nmcli dev show ${device} \
-        | awk -F ':' '/IP4.DNS/ {print $NF;}' \
-        | sed 's/ //g')
+	device="${1}"
+	printf '[DNS]: %s\n' $(nmcli dev show ${device} \
+		| awk -F ':' '/IP4.DNS/ {print $NF;}' \
+		| sed 's/ //g' \
+        | tee ~/.local/state/dns)
 
-    # add 34 to your signal
-    ${reloaddwmblocks} 2>/dev/null
+	# add 34 to your signal
+	${reloaddwmblocks} 2>/dev/null
 }
 # }}}
 
 case "${1}" in
-    -p|-print) printdns ;;
-    *) setdns ${@} ;;
+	-p|-print) printdns ;;
+	*) setdns ${@} ;;
 esac
