More scripts; better log/print message; add/improve args

diff --git a/bin/imagemagick-append b/bin/imagemagick-append
--- a/bin/imagemagick-append
+++ b/bin/imagemagick-append
@@ -10,6 +10,8 @@
 icon="imagemagick"
 stamp="$(date +%y%m%d_%H%M%S)"
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 ## help function {{{
 #help() {
@@ -39,10 +41,10 @@ prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
 # argument parsing {{{
 while [ "${#}" -gt 0 ]; do
 	case ${1} in
-#		-s|--style)
-#			style="${2}"
-#			shift
-#			;;
+		-o|--output)
+			output="${2}"
+			shift
+			;;
 		-i|--input)
 			images="${2}"
 			shift
@@ -108,19 +110,21 @@ notify() {
 }
 # }}}
 
+if [ -z "${output}" ]; then
+	name="screenshots_merged_${stamp}.png"
+else
+	name="${output}"
+fi
+
+printf '%s: %s ' ${prompt} ${name}
 ## conversion
-convert -append ${images} screenshots_merged_${stamp}.png >/dev/null 2>&1
+convert -append ${images} "${name}" >/dev/null 2>&1
 
 if [ $? -eq 0 ]; then
-	printf '✓\n'
+	printf '%s\n' ${ok}
+    exit 0
 else
-	printf '×\n'
+	printf '%s\n' ${err} 1>&2
+    exit 1
 fi
 
-## send notification if it was successful
-if [ "${?}" -eq 0 ]; then
-	if [ -f "screenshots_merged_${stamp}.png" ]; then
-		notify 'Images merged' \
-			"Output: ${PWD}/screenshots_merged_${stamp}.png"
-	fi
-fi
diff --git a/bin/imagemagick-color b/bin/imagemagick-color
--- a/bin/imagemagick-color
+++ b/bin/imagemagick-color
@@ -8,6 +8,8 @@
 
 # varaibles {{{
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 # help function {{{
 help() {
@@ -100,7 +102,7 @@ printf '%s\t' "${output}"
 convert ${input} -fuzz ${percent}% -fill ${find} -opaque ${replace} ${output}
 
 if [ $? -eq 0 ]; then
-	printf '✓\n'
+	printf '%s\n' ${ok}
 else
-	printf '×\n'
+	printf '%s\n' ${err} 1>&2
 fi
diff --git a/bin/imagemagick-gradiant b/bin/imagemagick-gradiant
--- a/bin/imagemagick-gradiant
+++ b/bin/imagemagick-gradiant
@@ -8,6 +8,9 @@
 
 # varaibles {{{
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 # help function {{{
 help() {
@@ -25,6 +28,7 @@ usage: [-hf] [-i input] [-o output] [-bg color] [-sc color] [-bc color]
 
        -bc --bcolor       border color (default: none)
        -bw --bwidth       border width (default: 0)
+       -br --brate        border rate  (default: 40)
 
        -x  --sxpos        shadow x position (default: 1)
        -y  --sypos        shadow y position (default: 1)
@@ -46,23 +50,27 @@ EOF
 # argument parsing {{{
 while [ "${#}" -gt 0 ]; do
 	case ${1} in
-		-i|--input)       input="${2}";             shift  ;;
-		-o|--output)      output="${2}";            shift  ;;
-		-f|--force)       force_replace='true';     shift  ;;
+		-i|--input)        input="${2}";             shift  ;;
+		-o|--output)       output="${2}";            shift  ;;
+		-f|--force)        force_replace='true';     shift  ;;
 
-		-bg|--background) background_color="${2}";  shift  ;;
+        -cf|--colorfirst)  colorfirst="${2}";        shift  ;;
+        -cs|--colorsecond) colorsecond="${2}";       shift  ;;
 
-		-bc|--bcolor)     border_color="${2}";      shift  ;;
-		-bw|--bwidth)     border_width="${2}";      shift  ;;
+		-bg|--background)  background_color="${2}";  shift  ;;
 
-		-x|--sxpos)       x="${2}";                 shift  ;;
-		-y|--sypos)       y="${2}";                 shift  ;;
-		-sr|--srate)      shadow_rate="${2}";       shift  ;;
-		-sc|--scolor)     shadow_color="${2}";      shift  ;;
-		-sw|--swidth)     shadow_width="${2}";      shift  ;;
+		-bc|--bcolor)      border_color="${2}";      shift  ;;
+		-bw|--bwidth)      border_width="${2}";      shift  ;;
+		-br|--brate)       border_rate="${2}";       shift  ;;
 
-		-h|--help)        help;                     exit 0 ;;
-		*)  echo "Unknown parameter passed: ${1}";  exit 1 ;;
+		-x|--sxpos)        x="${2}";                 shift  ;;
+		-y|--sypos)        y="${2}";                 shift  ;;
+		-sr|--srate)       shadow_rate="${2}";       shift  ;;
+		-sc|--scolor)      shadow_color="${2}";      shift  ;;
+		-sw|--swidth)      shadow_width="${2}";      shift  ;;
+
+		-h|--help)         help;                     exit 0 ;;
+		*)  echo "Unknown parameter passed: ${1}";   exit 1 ;;
 	esac
 	shift
 done
@@ -91,6 +99,15 @@ if [ -z "${output}" ]; then
 	fi
 fi
 
+if [ -z "${colorfirst}" ]; then
+	# colorfirst='#ff5577'
+	colorfirst='#ff7700'
+fi
+
+if [ -z "${colorsecond}" ]; then
+	colorsecond='#770000'
+fi
+
 if [ -z "${shadow_color}" ]; then
 	shadow_color="black"
 fi
@@ -101,6 +118,10 @@ fi
 
 if [ -z "${border_width}" ]; then
 	border_width="0"
+fi
+
+if [ -z "${border_rate}" ]; then
+	border_rate="40"
 fi
 
 if [ -z "${border_color}" ]; then
@@ -123,6 +144,7 @@ if [ -z "${y}" ]; then
 	y="1"
 fi
 # }}}
+
 # }}}
 
 printf "${prompt}: ${input} => "
@@ -133,10 +155,10 @@ if [ -z "${#}" ]; then
 fi
 
 res=$(identify "${input}" | awk '{print $3;}')
-resX=$( expr $(echo ${res} | awk -F 'x' '{print $1;}') + 40 )
-resY=$( expr $(echo ${res} | awk -F 'x' '{print $2;}') + 40 )
+resX=$( expr $(echo ${res} | awk -F 'x' '{print $1;}') + ${border_rate} )
+resY=$( expr $(echo ${res} | awk -F 'x' '{print $2;}') + ${border_rate} )
 
-echo "${res}: ${resX} x ${resY}"
+# echo "${res}: ${resX} x ${resY}"
 # resX=1558 # 1598 :40
 # resY=1237 # 1277 :40
 #
@@ -153,7 +175,7 @@ echo "${res}: ${resX} x ${resY}"
 
 $(which convert) \
 	-size ${resX}x${resY} \
-	gradient:'#ff5577'-'#770000' \
+	gradient:"${colorfirst}-${colorsecond}" \
 	${input} \
 	-bordercolor ${border_color} \
 	-border ${border_width} \( \
@@ -167,7 +189,7 @@ $(which convert) \
 	# 2>/dev/null
 
 if [ $? -eq 0 ]; then
-	printf "${output} ✓\n"
+	printf "${output} %s\n" ${ok}
 else
-	printf "${output} ×\n" > /dev/stderr
+	printf "${output} %s\n" ${err} > /dev/stderr
 fi
diff --git a/bin/imagemagick-round b/bin/imagemagick-round
--- a/bin/imagemagick-round
+++ b/bin/imagemagick-round
@@ -7,6 +7,9 @@
 
 # varaibles {{{
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 # help function {{{
 help() {
@@ -18,12 +21,12 @@ usage: [-h] [-i input] [-o output]
    • arguemts:
        -i --input      intput x
        -o --output     output y
-       -r --round      border rounding percentage
+       -r --round      border rounding percentage (default 25)
        -e --args       extra args (to pass to the launcher)
        -h --help       print this message
 
    • example:
-       ${prompt} -i in -o out
+       ${prompt} -i in -o out -r 15
 
    • running without any arguments will show this message
 EOF
@@ -83,14 +86,16 @@ sqrp="${persent}"
 
 ## get dementions:
 # identify "${input}" | awk '{print $3;}'
-dxmax=$(identify ${input} \
+tmp=$(identify ${input})
+dxmax=$(echo ${tmp} \
 	| awk '{print $3;}' \
 	| awk -F 'x' '{print $1;}')
 
-dymax=$(identify ${input} \
+dymax=$(echo ${tmp} \
 	| awk '{print $3;}' \
 	| awk -F 'x' '{print $2;}')
 
+printf '%s: %s => %s ' ${prompt} ${input} ${output}
 convert \
 	${input} \( \
 		+clone \
@@ -101,4 +106,12 @@ convert \
 	\) \
 	-channel-fx '| gray=>alpha'\
 	${output}
+
+if [ $? -eq 0 ]; then
+    printf '%s\n' ${ok}
+    exit 0
+else
+    printf '%s\n' ${err} 1>&2
+    exit 1
+fi
 
diff --git a/bin/imagemagick-shadow b/bin/imagemagick-shadow
--- a/bin/imagemagick-shadow
+++ b/bin/imagemagick-shadow
@@ -8,6 +8,9 @@
 
 # varaibles {{{
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 # help function {{{
 help() {
@@ -145,7 +148,7 @@ $(which convert) \
 	2>/dev/null
 
 if [ $? -eq 0 ]; then
-	printf "${output} ✓\n"
+	printf "${output} %s\n" ${ok}
 else
-	printf "${output} ×\n"
+	printf "${output} %s\n" ${err} 1>&2
 fi
diff --git a/bin/imagemagick-src b/bin/imagemagick-src
--- a/bin/imagemagick-src
+++ b/bin/imagemagick-src
@@ -1,36 +1,234 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #  _  _ ___
 # | || | __| P
 # | __ | _|
 # |_||_|___| J
 #
 
-bg="#002b36"
-fg="#ccccee"
-input="${1}"
-output="${2}"
+# varaibles {{{
+prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+
+ok='[DONE]'
+err='[FAIL]'
+# }}}
+# help function {{{
+help() {
+cat << EOF
+${prompt}: create image from source code with syntax highlight
+
+usage: [-h] [-i input] [-o output] [-bg color] [-fg color] [-t theme]
+            [-f font] [-s size]
+
+   • arguemts:
+       -h --help         print this message
+       -i --input        intput x
+       -o --output       output y
+
+       -f --font         font name
+       -s --size         font size
+       -t --theme        highlight theme
+
+       -bg --background  background color
+       -fg --foreground  foreground color
+
+   • example:
+       ${prompt} -i file.c -o file.c.png -bg black -fg white -t solarized-dark -f 'Ubuntu Mono' -s 32
+
+   • running without any arguments will show this message
+EOF
+}
+# }}}
+# argument parsing {{{
+while [ "${#}" -gt 0 ]; do
+case ${1} in
+	-i|--input)
+		input="${2}"
+		shift
+		;;
+	-o|--output)
+		output="${2}"
+		shift
+		;;
+	-h|--help)
+		help
+		exit 0
+		;;
+	-g|--gradiant)
+        gradiant="true"
+		;;
+	-t|--theme)
+		theme="${2}"
+		shift
+		;;
+	-f|--font)
+		font="${2}"
+		shift
+		;;
+	-s|--size)
+		size="${2}"
+		shift
+		;;
+	-bg|--background)
+		bgcolor="${2}"
+		shift
+		;;
+	-fg|--foreground)
+		fgcolor="${2}"
+		shift
+		;;
+	-e|--extra)
+		extra="${2}"
+		shift
+		;;
+	*)
+		echo "Unknown parameter passed: ${1}"
+		exit 1
+		;;
+esac
+shift
+done
+
+# checking args {{{
+
+[ -f "${HOME}/.cache/wal/colors.sh" ] && source "${HOME}/.cache/wal/colors.sh"
+
+if [ -z "${input}" ]; then
+    printf '%s\n\n' "No input is specified" 1>&2
+    help
+    exit 1
+fi
+
+if [ -z "${output}" ]; then
+    printf '%s\n\n' "No output is specified" 1>&2
+    help
+    exit 2
+fi
+
+[ -z "${bgcolor}" ] && bgcolor="${background}"
+[ -z "${fgcolor}" ] && fgcolor="${foreground}"
+[ -z "${font}" ] && font="Monospace"
+[ -z "${size}" ] && size="32"
+[ -z "${color5}" ] && grad_first='#770000' || grad_first="${color5}"
+[ -z "${color4}" ] && grad_second='#ff7700' || grad_second="${color4}"
+
+[ -z "${theme}" ] && theme="edit-vim-dark"
+# theme="edit-vim-dark"
+# theme="xoria256"
+# theme="edit-godot"
+
+# }}}
+
+# }}}
+
+## launcher {{{
+# vars and args {{{
+#icon=""
+#path="${HOME}/.local/hos/chars/emoji.txt"
+#patched="-bw 0 -g 4 -l 10"
+#style=""
+#eargs=""
+# }}}
+#
+#if [ "${style}" = 'tui' ]; then
+#	runner="fzf -i -m \
+#			--reverse \
+#			--border=sharp \
+#			--info=inline \
+#			--prompt=: \
+#			--marker=* \
+#			--header=${prompt} --header-first \
+#			${args} \
+#			"
+#elif [ -z ${DISPLAY} ]; then
+#	runner="fzf -i -m \
+#			--reverse \
+#			--no-unicode \
+#			--info=inline \
+#			--border=sharp --border-label=${prompt} \
+#			--prompt=: \
+#			--marker=* \
+#			${args} \
+#			"
+#elif [ "${style}" = 'gui' ]; then
+#	runner="dmenu -l 9 -p ${prompt} ${patched} ${eargs}"
+#else
+#	runner="dmenu -l 9 -p ${prompt} ${patched} ${eargs}"
+#fi
+## }}}
+## notification function {{{
+#notify() {
+#	summary="${1}"
+#	if [ -z "${2}" ] || [ "${2}" = 1 ] || [ "${2}" = 2 ] || [ "${2}" = 3 ]; then
+#		case ${2} in
+#			1) mode=low ;;
+#			2) mode=normal ;;
+#			3) mode=critical ;;
+#			*) mode=normal ;;
+#		esac
+#		#msgbody="${3}"
+#	else
+#		case ${3} in
+#			1) mode=low ;;
+#			2) mode=normal ;;
+#			3) mode=critical ;;
+#			*) mode=normal ;;
+#		esac
+#		msgbody="${2}"
+#	fi
+#
+#	if [ ${mode} = 'critical' ]; then
+#		iferror="stderr"
+##		icon='error'
+#	else
+#		iferror="stdout"
+#	fi
+#
+#	if [ -n "${icon}" ]; then
+#		noticon="-i ${icon}"
+#	fi
+#
+#	if [ "${style}" = 'tui' ]; then
+#		printf '[%s] %s\n' "${summary}" "${msgbody}" "${iferror}"
+#	elif [ -z "${DISPLAY}" ]; then
+#		echo "${@}" >/dev/null 2>&1
+#	else
+#		notify-send -a "${prompt}" -u ${mode} ${noticon} \
+#			"${summary}" "${msgbody}" 2>/dev/null
+#		printf '[%s] %s\n' "${summary}" "${msgbody}" >/dev/${iferror}
+#	fi
+#}
+## }}}
 
 highlight \
 		-i "${input}" \
 		-O pango \
 		-P \
-		-T "This is a simple test!" \
+        ${extra} \
 		-l \
 		-j 5 \
-		-k "Fira Mono" \
-		-K 38 \
-		-s solarized-dark \
+		-k "${font}" \
+		-K ${size} \
+		-s ${theme} \
 		-t 4 \
-	| convert \
-		-background "${bg}" \
-		-fill "${fg}" \
+    | $(which convert || which magick) \
+		-background "${bgcolor}" \
+		-fill "${fgcolor}" \
 		pango:@- \
-		-size 800x \
+		-size 800x1000 \
 		-background none \
 		"${output}"
 
 imagemagick-trim -i "${output}" -o "${output}"
-imagemagick-shadow -i "${output}" -o "${output}" -sw 0 -sc none -bw 50 -bc "${bg}"
+imagemagick-shadow -i "${output}" -o "${output}" -sw 0 -sc none -bw 50 -bc "${bgcolor}"
 imagemagick-trim -i "${output}" -o "${output}"
-~/dev/primejade/hos-workflow/scripts/imagemagick-round -i "${output}" -o "${output}" -r 30
-~/dev/primejade/hos-workflow/scripts/imagemagick-gradiant -i "${output}" -o "${output}"
+imagemagick-round -i "${output}" -o "${output}" -r 15
+
+if [ ! -z ${gradiant} ]; then
+    imagemagick-gradiant -i "${output}" -o "${output}" -cf "${grad_first}" -cs "${grad_second}"
+fi
+
+if [ $? -eq 0 ]; then
+	printf "${prompt}: ${input} => ${output} %s\n" ${ok}
+else
+	printf "${prompt}: ${input} => ${output} %s\n" ${err} > /dev/stderr
+fi
diff --git a/bin/imagemagick-string b/bin/imagemagick-string
--- a/bin/imagemagick-string
+++ b/bin/imagemagick-string
@@ -8,6 +8,9 @@
 
 # varaibles {{{
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
+
+ok='[DONE]'
+err='[FAIL]'
 # }}}
 # help function {{{
 help() {
@@ -203,9 +206,9 @@ convert \
 	${output}
 
 if [ $? -eq 0 ]; then
-	printf '✓\n'
+	printf '%s\n' ${ok}
 else
-	printf '×\n'
+	printf '%s\n' ${err} 1>&2
 fi
 
 # if [ "${trim}" = "true" ]; then
diff --git a/bin/imagemagick-trim b/bin/imagemagick-trim
--- a/bin/imagemagick-trim
+++ b/bin/imagemagick-trim
@@ -6,14 +6,17 @@
 # |_|   \___/ 
 #             
 
-## varaibles {{{
-#icon=""
-#path="${HOME}/.local/hos/chars/emoji.txt"
+# varaibles {{{
+# icon=""
+# path="${HOME}/.local/hos/chars/emoji.txt"
 prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
-#patched="-bw 0 -g 4 -l 10"
-#style=""
-#eargs=""
-## }}}
+# patched="-bw 0 -g 4 -l 10"
+# style=""
+# eargs=""
+
+ok='[DONE]'
+err='[FAIL]'
+# }}}
 # help function {{{
 help() {
 cat << EOF
@@ -85,9 +88,9 @@ if [ "${loopit}" = 'true' ]; then
 		convert -trim ${input} ${output}
 
 		if [ $? -eq 0 ]; then
-			printf '✓\n'
+			printf '%s\n' ${ok}
 		else
-			printf '×\n'
+			printf '%s\n' ${err} 1>&2
 		fi
 	done
 else
@@ -96,8 +99,8 @@ else
 	convert -trim ${input} ${output}
 
 	if [ $? -eq 0 ]; then
-		printf '✓\n'
+		printf '%s\n' ${ok}
 	else
-		printf '×\n'
+		printf '%s\n' ${err} 1>&2
 	fi
 fi
